### ISSUE TITLE
you can have this as a @RequestMapping at the Controller lever, and you will not need to concatenate this to every other request manually, it will be done automatically

### ISSUE THREAD

**Issue by bogdaniancudd** [paul911/rest_api_assignment#1]
https://github.com/paul911/rest_api_assignment/blob/6c1be8ef28bb74468d41af42b116e0de3d4ca6f6/src/main/java/assignment/controllers/TransactionsController.java#L21

**Comment by paul911** [comment]
Fixed issue with commit 4b6f5650a191229ff2dde229808809b7c981b6a6
